export type Discipline = "percepcao" | "acao" | "vontade";

export type MonthTheme =
  | "janeiro_clareza"
  | "fevereiro_paixoes_e_emocoes"
  | "marco_consciencia"
  | "abril_pensamento_imparcial"
  | "maio_acao_correta"
  | "junho_solucao_de_problemas"
  | "julho_dever"
  | "agosto_pragmatismo"
  | "setembro_forca_e_resiliencia"
  | "outubro_virtude_e_bondade"
  | "novembro_aceitacao_amor_fati"
  | "dezembro_meditacao_sobre_a_mortalidade";

export interface StoicQuote {
  text: string;
  author: string;
  discipline: Discipline;
  monthTheme: MonthTheme;
}

export const STOIC_QUOTES_ORGANIZED: StoicQuote[] = [
  // JANEIRO — CLAREZA
  {
    text: "A liberdade é o maior bem.",
    author: "Catão, o Jovem",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A sabedoria é o guia da liberdade.",
    author: "Catão, o Jovem",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A razão é a luz do mundo.",
    author: "Crísipo",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "Algumas coisas dependem de nós e outras não.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "O que importa não é o que acontece com você, mas como você reage a isso.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "Onde está o bem? Na escolha. Onde está o mal? Na escolha.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A felicidade e a liberdade começam com a compreensão de um princípio: algumas coisas estão sob nosso controle e outras não.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A verdadeira educação consiste em aprender a distinguir o que é nosso do que não é.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A filosofia não promete assegurar nada externo ao homem.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "Não busques o bem fora de ti mesmo.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A razão é o guia da vida.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A razão é a bússola da vida.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A nossa vida é aquilo que os nossos pensamentos fizerem dela.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A primeira regra é manter o espírito tranquilo. A segunda é enfrentar as coisas de frente e tomá-las pelo que realmente são.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A tranquilidade nada mais é do que a boa ordenação da mente.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "Não se deixe levar pelos acidentes externos.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A razão é o guia soberano.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "Não se pode viver bem sem filosofar.",
    author: "Musônio Rufo",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "Nenhum vento sopra a favor de quem não sabe para onde ir.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },
  {
    text: "A paz de espírito é o maior bem.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "janeiro_clareza",
  },

  // FEVEREIRO — PAIXÕES E EMOÇÕES
  {
    text: "Não são as coisas que nos perturbam, mas sim as nossas opiniões sobre elas.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Se alguém fala mal de você, não se defenda, mas diga: 'Ele deve não conhecer meus outros defeitos'.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Ninguém pode te ferir a menos que você consinta.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Não sejas escravo de teus desejos.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "A moderação é a chave para a paz.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Se fores atacado por alguém, lembra-te que é a tua opinião que te ataca.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "A liberdade começa onde o desejo termina.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "A alma fica tingida com a cor dos seus pensamentos.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "A felicidade de sua vida depende da qualidade de seus pensamentos.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Nenhum homem é feliz se não se considera feliz.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Mais penosas são as consequências da ira do que as suas causas.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Quanto não ganha em tranquilidade quem não se preocupa com o que o vizinho diz.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "O homem sábio não busca o prazer, mas a ausência de dor.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Não sejas um escravo de teus impulsos.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "A temperança é o controle dos prazeres.",
    author: "Musônio Rufo",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "O vício é a doença da alma.",
    author: "Musônio Rufo",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Pobre não é aquele que tem pouco, mas aquele que deseja mais.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "O maior remédio para a ira é o adiamento.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "A escravidão mais degradante é a de ser escravo de si mesmo.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "A amizade sempre aproveita, o amor às vezes fere.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "O homem que sofre antes de ser necessário, sofre mais que o necessário.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "A mente que está ansiosa pelo futuro é miserável.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "A sabedoria consiste em não desejar o que não é necessário.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Nada é tão lamentável e nocivo como antecipar desgraças.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "As coisas que nos assustam são em maior número do que as que efetivamente fazem mal.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "Desventurado é aquele que por tal se julga.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },
  {
    text: "O medo é um mau conselheiro.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "fevereiro_paixoes_e_emocoes",
  },

  // MARÇO — CONSCIÊNCIA
  {
    text: "A felicidade é o fim supremo da vida.",
    author: "Cleantes",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "O universo é governado pela razão divina.",
    author: "Crísipo",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A sabedoria é o tesouro do mundo.",
    author: "Crísipo",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A prudência é a melhor parte do valor.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "Se desejas ser bom, primeiro acredita que és mau.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "Não te vanguries de tua sabedoria.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "O sábio é aquele que conhece a si mesmo.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A sabedoria é o tesouro mais precioso.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A razão é a luz da alma.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A sabedoria é o guia supremo.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A sabedoria é a fonte da felicidade.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A razão é o dom da natureza.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A sabedoria é a luz da mente.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A sabedoria é o fruto da experiência.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "O valor de um homem é medido pelo valor das coisas que ele valoriza.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "O universo é mudança; nossa vida é o que nossos pensamentos a fazem.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "Escava dentro de ti. É lá que está a fonte do bem.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "Olhe para dentro. Dentro está a fonte do bem, e esta pode jorrar continuamente, se a escavares sempre.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "Lembre-se de que o homem vive apenas no presente, neste instante fugaz.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "O tempo é um tipo de rio de eventos, e sua corrente é forte.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "Cada coisa existe para algum fim.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A natureza do universo é a natureza de tudo o que existe.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A alma racional percorre todo o universo e o vácuo que o cerca.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A alma é um objeto esférico quando não se estende para nada externo.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A natureza não faz nada em vão.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A lei é a razão suprema implantada na natureza.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "O universo é um ser vivo.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A natureza é a mãe de todos.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A razão é o guia da alma.",
    author: "Musônio Rufo",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A sabedoria é o tesouro do sábio.",
    author: "Musônio Rufo",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A razão é o dom da humanidade.",
    author: "Musônio Rufo",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A consciência do pecado é o primeiro passo para a salvação.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A maior parte da vida escapa daqueles que fazem o mal.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "Os vícios são próprios dos homens e não dos tempos.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "O tempo é o melhor professor.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A natureza é o melhor guia.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "O homem é um ser racional.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A sabedoria é a luz da alma.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A razão é o dom supremo.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A vida é um dom da razão.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "O mundo é um ser vivo e racional.",
    author: "Zenão de Cítio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A razão é a lei universal.",
    author: "Zenão de Cítio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A sabedoria é a virtude intelectual.",
    author: "Zenão de Cítio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A alma é um sopro, mas a razão é divina.",
    author: "Zenão de Cítio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A natureza é a lei suprema.",
    author: "Zenão de Cítio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },
  {
    text: "A natureza é o espelho da razão.",
    author: "Zenão de Cítio",
    discipline: "percepcao",
    monthTheme: "marco_consciencia",
  },

  // ABRIL — PENSAMENTO IMPARCIAL
  {
    text: "O silêncio é uma virtude quando a fala é inútil.",
    author: "Catão, o Jovem",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "A razão é a lei.",
    author: "Cleantes",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Se não houvesse o mal, não haveria o bem.",
    author: "Crísipo",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "O sábio não tem opiniões, ele tem conhecimento.",
    author: "Crísipo",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "É impossível para um homem aprender o que ele acha que já sabe.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "A verdade é a única coisa que liberta.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "O silêncio é mais seguro do que a fala.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "O homem sábio ouve mais do que fala.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Tudo o que ouvimos é uma opinião, não um fato. Tudo o que vemos é uma perspectiva, não a verdade.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Tudo o que é belo, é belo por si mesmo.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "A razão é a mesma para todos os seres racionais.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Se alguém puder me refutar e me mostrar que estou enganado, mudarei de bom grado.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Mudar de opinião e seguir quem te corrige é também o comportamento do homem livre.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "A vida não é boa nem má, mas apenas um lugar para o bem e o mal.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "A verdade nunca fere ninguém; o que fere é persistir no erro e na ignorância.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Não sejas um homem de muitas palavras.",
    author: "Marco Aurélio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Toda arte é imitação da natureza.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Quem decide sem ouvir a outra parte, embora decida com justiça, não é justo.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Cala-te primeiro se queres que os outros se calem.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Lágrimas de herdeiros são risos mascarados.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "A verdade é simples.",
    author: "Sêneca",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "Temos dois ouvidos e uma boca para ouvirmos mais e falarmos menos.",
    author: "Zenão de Cítio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },
  {
    text: "A natureza é a fonte da verdade.",
    author: "Zenão de Cítio",
    discipline: "percepcao",
    monthTheme: "abril_pensamento_imparcial",
  },

  // MAIO — AÇÃO CORRETA
  {
    text: "A liberdade é o poder de agir por si mesmo.",
    author: "Crísipo",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "O sábio nunca se arrepende de suas ações.",
    author: "Crísipo",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "Não explique sua filosofia, mas sim incorpore-a.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "Primeiro diga a si mesmo o que você seria; então faça o que precisa ser feito.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "Se você quer ser algo, comece por ser algo.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "Muitas vezes erra não apenas quem faz, mas também quem deixa de fazer alguma coisa.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "Se te ocorrer, de manhã, de acordares com preguiça e indolência, lembra-te deste pensamento: 'Levanto-me para retomar a minha obra de homem'.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "Não perca mais tempo discutindo sobre o que um homem bom deve ser. Seja um.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "Não sejas negligente em tuas ações, nem confuso em tuas palavras.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "A felicidade do homem depende de si mesmo.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "Pratica cada um dos teus atos como se fosse o último da tua vida.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "A filosofia é nada mais que a busca pela vida correta.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "O trabalho é um bem, pois afasta o vício.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "A filosofia ensina a agir, não a falar.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "Ninguém chegou a ser sábio por acaso.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },
  {
    text: "O sábio é o arquiteto de sua vida.",
    author: "Zenão de Cítio",
    discipline: "acao",
    monthTheme: "maio_acao_correta",
  },

  // JUNHO — SOLUÇÃO DE PROBLEMAS
  {
    text: "Tudo tem duas alças: uma pela qual pode ser carregado e outra pela qual não pode.",
    author: "Epicteto",
    discipline: "percepcao",
    monthTheme: "junho_solucao_de_problemas",
  },
  {
    text: "A sorte é o que acontece quando a preparação encontra a oportunidade.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "junho_solucao_de_problemas",
  },
  {
    text: "Muitas coisas não ousamos empreender por parecerem difíceis; entretanto, são difíceis porque não ousamos empreendê-las.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "junho_solucao_de_problemas",
  },
  {
    text: "É parte da cura o desejo de ser curado.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "junho_solucao_de_problemas",
  },

  // JULHO — DEVER
  {
    text: "A justiça é a base da liberdade.",
    author: "Catão, o Jovem",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é o equilíbrio do mundo.",
    author: "Crísipo",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A liberdade é o único objetivo digno na vida.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "Nenhum homem é livre se não for mestre de si mesmo.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O sol não espera por orações para nascer; faça o bem da mesma forma.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O principal dever do homem é a sinceridade.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é o dever de todos.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é o fundamento da sociedade.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O sábio é mestre de si mesmo.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é a lei suprema.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "Devemos cuidar de nós mesmos para cuidar dos outros.",
    author: "Hierócles",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O círculo da preocupação começa no indivíduo e se expande para a humanidade.",
    author: "Hierócles",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O que não é bom para a colmeia, não é bom para a abelha.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "Onde há um homem, há uma oportunidade para a justiça.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O mundo é uma única cidade.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O homem é um animal social.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça consiste em dar a cada um o que lhe é devido.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "As mulheres devem filosofar tanto quanto os homens.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A obediência aos pais é um dever, a menos que ordenem o mal.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O mestre deve ensinar pelo exemplo.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é a base da sociedade.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O sábio é cidadão do mundo.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é o dever do sábio.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O que a lei não proíbe, a honestidade pode proibir.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "Possuir um bem, sem o partilhar, não tem qualquer atrativo.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O exemplo convence-nos mais do que as palavras.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O sábio é senhor de si mesmo.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é o fundamento do Estado.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é o vínculo da sociedade.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é o fundamento da ordem.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é a luz da sociedade.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "A justiça é a virtude social.",
    author: "Zenão de Cítio",
    discipline: "acao",
    monthTheme: "julho_dever",
  },
  {
    text: "O sábio é o único homem livre.",
    author: "Zenão de Cítio",
    discipline: "acao",
    monthTheme: "julho_dever",
  },

  // AGOSTO — PRAGMATISMO
  {
    text: "O homem livre é aquele que vive como deseja.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A riqueza não consiste em ter grandes posses, mas em ter poucas necessidades.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "O tempo é o recurso mais precioso.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A felicidade não é um destino, é um modo de vida.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A vida é curta, a arte é longa.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A vida é curta. Aproveite o presente com alegria e justiça.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A vida é uma arte.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A dieta simples é a melhor para o corpo e a alma.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "O luxo corrompe o caráter.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A prática é mais importante que a teoria.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A vida rural é propícia à virtude.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "Não é que tenhamos pouco tempo, é que perdemos muito.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A vida, se bem empregada, é suficientemente longa.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "Enquanto adiamos, a vida passa.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "Nada é nosso, exceto o tempo.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "O ócio sem letras é a morte e a sepultura do homem vivo.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "Não recebemos uma vida curta, mas fazemo-la curta.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "Para a nossa avareza, o muito é pouco; para a nossa necessidade, o pouco é muito.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "Se vives de acordo com as leis da natureza, nunca serás pobre.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A fome não é exigente: basta contentá-la.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A vida é uma escola de sabedoria.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },
  {
    text: "A felicidade é um bom fluxo de vida.",
    author: "Zenão de Cítio",
    discipline: "acao",
    monthTheme: "agosto_pragmatismo",
  },

  // SETEMBRO — FORÇA E RESILIÊNCIA
  {
    text: "A coragem é a alma da liberdade.",
    author: "Catão, o Jovem",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a força do mundo.",
    author: "Crísipo",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A marca da sabedoria é não ser perturbado pelo que não depende de nós.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "O filósofo deve ser como um atleta da alma.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A paciência é o remédio para todas as dores.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a resistência ao medo, não a ausência dele.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a força da alma.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é o desprezo pelo medo.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A vida é um combate constante.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a vitória sobre si mesmo.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a força do caráter.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A sabedoria é o guia da vontade.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "Nada de desgosto, nem de desânimo; se acabas de fracassar, recomeça.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "Nada acontece a qualquer homem que ele não seja formado pela natureza para suportar.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A arte de viver é mais parecida com a luta do que com a dança.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "Onde é possível viver, é possível viver bem.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A mente livre de paixões é uma fortaleza.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A vida é uma batalha e uma estadia em terra estranha.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "Não te perturbes com o futuro; tu o enfrentarás com as mesmas armas da razão.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "O sábio é livre de medos.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é o escudo da alma.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a vitória sobre o medo.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a força do espírito.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a firmeza da vontade.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "O exílio não é um mal para quem tem virtude.",
    author: "Musônio Rufo",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A dor física deve ser suportada com coragem.",
    author: "Musônio Rufo",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A alma é fortalecida pela privação.",
    author: "Musônio Rufo",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a força do sábio.",
    author: "Musônio Rufo",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "As dificuldades fortalecem a mente, assim como o trabalho fortalece o corpo.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "Ninguém é mais infeliz do que aquele que nunca enfrentou a adversidade.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "O tempo cura o que a razão não consegue.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "O fogo é a prova do ouro; a miséria, a do homem forte.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "Viver significa lutar.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "O sábio é auto-suficiente.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "O dia seguinte é sempre o pior.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "Quanto mais violenta a tempestade, tanto menor a sua duração.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "O sábio nunca está sozinho.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A dor é inevitável, o sofrimento é opcional.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a base de todas as virtudes.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A vida é um combate perpétuo.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é o desprezo pelo perigo.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A vida é um combate pela virtude.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "A coragem é a virtude individual.",
    author: "Zenão de Cítio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },
  {
    text: "O sábio é o mestre de seu destino.",
    author: "Zenão de Cítio",
    discipline: "vontade",
    monthTheme: "setembro_forca_e_resiliencia",
  },

  // OUTUBRO — VIRTUDE E BONDADE
  {
    text: "Prefiro ser um homem de mérito do que um homem de nascimento.",
    author: "Catão, o Jovem",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A honra é mais preciosa que a vida.",
    author: "Catão, o Jovem",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é suficiente para a felicidade.",
    author: "Cleantes",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "O caráter é o destino.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é a sua própria recompensa.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A amizade verdadeira é baseada na virtude.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A sabedoria é o caminho para a paz.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é a única beleza.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A justiça é a base da paz.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A vida é uma jornada para a virtude.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é a única riqueza.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é o caminho para a felicidade.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é a única beleza real.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é o único bem imperecível.",
    author: "Epicteto",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A família é a primeira escola da virtude.",
    author: "Hierócles",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A melhor vingança é não ser como seu inimigo.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "Abster-se de imitar é a melhor vingança.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A justiça é a fonte de todas as outras virtudes.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "Mantenha-se simples, bom, puro, sério, livre de afetação, amigo da justiça.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "O que é um homem bom? Alguém que é justo, temperante, corajoso e livre.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "O sol brilha também sobre os pântanos e não se suja.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é a única coisa que importa.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A paciência é uma parte da justiça.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "Não sejas um hipócrita.",
    author: "Marco Aurélio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "Para o homem, a virtude é o único bem real.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "O casamento deve ser uma união de almas e corpos para a virtude.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A modéstia é o ornamento da juventude.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é a saúde da alma.",
    author: "Musônio Rufo",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "Onde quer que haja um ser humano, há uma oportunidade para a bondade.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é o único bem.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A amizade é uma alma em dois corpos.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "Se quiseres ser amado, ama.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A deformidade do corpo não afeia uma bela alma.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude não precisa de ornamentos.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A justiça é a rainha das virtudes.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é a única nobreza.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A sabedoria é o caminho para a felicidade.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude não é outra coisa senão a razão correta.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A justiça é a base da amizade.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A vida é um teatro de virtudes.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A justiça é a harmonia da alma.",
    author: "Sêneca",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A virtude é uma disposição harmoniosa.",
    author: "Zenão de Cítio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },
  {
    text: "A natureza é a mãe da virtude.",
    author: "Zenão de Cítio",
    discipline: "acao",
    monthTheme: "outubro_virtude_e_bondade",
  },

  // NOVEMBRO — ACEITAÇÃO / AMOR FATI
  {
    text: "O destino guia quem o aceita e arrasta quem o resiste.",
    author: "Cleantes",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "Sem ti, ó Deus, nada acontece na terra.",
    author: "Cleantes",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vida é um dom.",
    author: "Cleantes",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vida é um teatro.",
    author: "Crísipo",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "Só existe um caminho para a felicidade, que é parar de se preocupar com coisas que estão além do poder da nossa vontade.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "Não espere que os eventos aconteçam como você deseja; deseje que eles aconteçam como acontecem.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "Quem é o homem rico? Aquele que está satisfeito.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "O sábio não se aflige pelo que não tem, mas se alegra pelo que tem.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vida é como uma peça de teatro; o que importa não é a duração, mas o desempenho.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vontade de Deus é a única lei.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "Aprenda a querer que tudo aconteça exatamente como acontece.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "O tempo é o senhor de tudo.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vida é uma jornada.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vida é um mistério.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "Tudo o que acontece, acontece como deve, e se você observar atentamente, verá que é assim.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "Aceite as coisas às quais o destino te amarra e ame as pessoas com as quais o destino te aproxima.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "Aquele que vive em harmonia consigo mesmo vive em harmonia com o universo.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A perda não é outra coisa senão mudança, e a mudança é o deleite da natureza.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "Tudo o que acontece a você foi preparado para você desde a eternidade.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "O que é a fama? Apenas um eco.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vida é um dom dos deuses.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "O verdadeiro filósofo não busca a fama.",
    author: "Musônio Rufo",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vida é um dom da natureza.",
    author: "Musônio Rufo",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "O destino conduz os que querem e arrasta os que não querem.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vida é uma peça de teatro.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "O tempo é o senhor de todas as coisas.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "A vida é um dom precioso.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "O objetivo da vida é viver em acordo com a natureza.",
    author: "Zenão de Cítio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "O destino é a causa de todas as coisas.",
    author: "Zenão de Cítio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },
  {
    text: "O sábio vive em harmonia com o todo.",
    author: "Zenão de Cítio",
    discipline: "vontade",
    monthTheme: "novembro_aceitacao_amor_fati",
  },

  // DEZEMBRO — MEDITAÇÃO SOBRE A MORTALIDADE
  {
    text: "A coragem é o desprezo pela morte.",
    author: "Catão, o Jovem",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A vida é curta, a glória é eterna.",
    author: "Catão, o Jovem",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é o fim da escravidão.",
    author: "Catão, o Jovem",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A alma é um sopro vital.",
    author: "Cleantes",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é um destino.",
    author: "Cleantes",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é um mistério.",
    author: "Crísipo",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte não é terrível, o terror está na nossa opinião sobre ela.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A alma é um pequeno corpo carregando um cadáver.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é o fim de todas as coisas.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é uma libertação.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte não é um mal.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é um sono profundo.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é uma passagem.",
    author: "Epicteto",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "Não desprezes a morte; dá-lhe boa acolhida, como a uma das coisas que a Natureza quer.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A brevidade da vida é comum a todos.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "Não ajas como se tivesses dez mil anos pela frente. A fatalidade paira sobre ti.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte sorri para todos nós; tudo o que um homem pode fazer é sorrir de volta.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A perfeição moral consiste em passar cada dia como se fosse o último.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "Tudo o que é material logo desaparece no universo.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é um descanso das impressões sensoriais.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "O que é o tempo? Um ponto no infinito.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é apenas uma mudança de estado.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "O tempo é um jogo de crianças, jogado por crianças.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é o retorno à natureza.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é o fim da dor.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é a libertação da alma.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é o destino comum.",
    author: "Marco Aurélio",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A alma é imortal.",
    author: "Musônio Rufo",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é uma lei da natureza.",
    author: "Musônio Rufo",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "Apressa-te a viver bem e pensa que cada dia é, por si só, uma vida.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "Apressa-te a viver e conta cada dia como uma vida separada.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é a libertação de todas as dores.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "Se queres suportar a vida, prepara-te para a morte.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A brevidade da vida é o maior de todos os males.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A velhice é um mal incurável.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A alma é maior do que o corpo.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte é um porto seguro.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
  {
    text: "A morte não é um fim, mas uma mudança.",
    author: "Sêneca",
    discipline: "vontade",
    monthTheme: "dezembro_meditacao_sobre_a_mortalidade",
  },
];
export const STOIC_QUOTES = STOIC_QUOTES_ORGANIZED;
